package com.arjunsports.contentagent.common.notification;

public enum NotificationType {
    LOGIN_SUCCESS,
    PASSWORD_CHANGED,
    GENERATION_COMPLETED,
    GENERATION_FAILED,
    DRAFT_SAVED,
    DRAFT_UPDATED,
    DRAFT_DELETED,
    DRAFT_RESTORED,
    APPROVAL_REQUIRED,
    APPROVED,
    REJECTED,
    APPROVAL_COMMENT_ADDED,
    PUBLISH_SUCCESS,
    PUBLISH_FAILURE,
    SCHEDULE_COMPLETED,
    SCHEDULE_FAILED,
    SYSTEM
}
