spring:
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    com.arjunsports.contentagent: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
